import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HeaderDomingocoSeven
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/headerdomingocoone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HeaderDomingocoOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/headerdomingocofour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HeaderDomingocoFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/macbookpro14one" style={{ color: "#87CEFA", textDecoration: "none" }}>
            MacBookPro14One
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/headerdomingocofive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HeaderDomingocoFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/headerdomingocotwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HeaderDomingocoTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/headerdomingocosix" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HeaderDomingocoSix
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/headerdomingoco" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HeaderDomingoco
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
